apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: movies
  name: movies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies
  template:
    metadata:      
      labels:
        app: movies
    spec:
      containers:
      - name: movies
        image: dmirina/movies:1.5
        ports:
          - containerPort: 8080
